Revert "exfat: free the sbi and iocharset in ->kill_sb"
This reverts commit 8269c2d7f032cdc59295a14d3418bda40be7c573.

Log:
../fs/exfat/super.c:1115:9: error: implicit declaration of function 'exfat_free_sbi'; did you mean 'exfat_free_inode'? [-Werror=implicit-function-declaration]
 1115 |         exfat_free_sbi(sbi);
      |         ^~~~~~~~~~~~~~
      |         exfat_free_inode

Signed-off-by: TogoFire <togofire@mailfence.com>
Change-Id: Ie7ad65ed921b1a4fdc02f2d138e9f8c0df18f3dc